// Copyright 2024 QMK -- generated source code only, image retains original copyright
// SPDX-License-Identifier: GPL-2.0-or-later

// This file was auto-generated by `qmk painter-convert-graphics --input /home/sven/Code/qmk_firmware/Zodipact240.png --output /home/sven/Code/qmk_firmware --format mono16 --no-rle False --no-deltas False`

#pragma once

#include <qp.h>

extern const uint32_t gfx_Zodipact240_length;
extern const uint8_t  gfx_Zodipact240[7075];
