# MCU name
MCU = STM32F401
BOARD = BLACKPILL_STM32_F401
RGB_MATRIX_ENABLE = yes     # Enable keyboard RGB matrix functionality
RGB_MATRIX_DRIVER = WS2812
WS2812_DRIVER = pwm
OLED_ENABLE = yes
OLED_DRIVER = SSD1306
EEPROM_DRIVER = i2c