POINTING_DEVICE_DRIVER = cirque_pinnacle_spi
POINTING_DEVICE_ENABLE = yes
MOUSEKEY_ENABLE = yes
OLED_ENABLE = yes
OLED_TRANSPORT = i2c
OLED_DRIVER = ssd1306
SPLIT_KEYBOARD = yes
CAPS_WORD_ENABLE = yes
